import = ["~/.dotfiles/alacritty/themes/one_dark.toml"]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
opacity = 0.9
startup_mode = "Windowed"
title = "Alacritty"
padding = { x = 5, y = 1 }

[window.dimensions]
columns = 90
lines = 40

[colors]
draw_bold_text_with_bright_colors = true

[font]
builtin_box_drawing = true
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "BoldItalic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[cursor]
unfocused_hollow = false

[shell]
program = "/bin/zsh"

[cursor.style]
shape = "Beam"
blinking = "On"

[mouse]
hide_when_typing = false

[keyboard]
# Emulate ctrl + backspace on editor
bindings = [{ key = "Back", mods = "Control", chars = "\u0017" }]
