# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Import additional configuration files
import:
    - ~/.dotfiles/alacritty/themes/one_dark.yaml

env:
    TERM: alacritty

window:
    dimensions:
        columns: 90
        lines: 40

    padding:
        x: 10
        y: 10

    decorations: none

    opacity: 0.95

    startup_mode: Windowed

    dynamic_title: true

    class:
        instance: Alacritty
        general: Alacritty

    decorations_theme_variant: Dark

# Font configuration
font:
    # Normal (roman) font face
    normal:
        #family: CaskaydiaCove Nerd Font Mono
        family: CaskaydiaCove Nerd Font Mono
        style: Regular

    # Bold font face
    bold:
        family: CaskaydiaCove Nerd Font Mono
        style: Bold

    # Italic font face
    italic:
        family: CaskaydiaCove Nerd Font Mono
        style: Italic

    # Bold italic font face
    bold_italic:
        family: CaskaydiaCove Nerd Font Mono
        style: Bold Italic

    size: 12.5

draw_bold_text_with_bright_colors: false

selection:
    semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

cursor:
    style:
        shape: Beam
        blinking: On

    blink_interval: 750

    blink_timeout: 5

    unfocused_hollow: false

live_config_reload: true

shell:
    program: /bin/zsh
